Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,15 +2,13 @@ name: Build APK
 
 on:
   workflow_dispatch:
-  push:
-    branches: [ main ]
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout
+      - name: Checkout repository
         uses: actions/checkout@v4
 
       - name: Set up Python
@@ -25,12 +23,25 @@ jobs:
             git zip unzip openjdk-17-jdk \
             build-essential autoconf automake libtool pkg-config
 
-      - name: Install Python deps
+      - name: Install Python dependencies
         run: |
           python -m pip install --upgrade pip
           pip install cython==0.29.37 buildozer
 
-      - name: Clean build
+      - name: Verify project files
+        run: |
+          echo "Current directory:"
+          pwd
+
+          echo "Files:"
+          ls -la
+
+          if [ ! -f buildozer.spec ]; then
+            echo "ERROR: buildozer.spec NOT FOUND"
+            exit 1
+          fi
+
+      - name: Clean Buildozer cache
         run: |
           rm -rf .buildozer
           rm -rf ~/.buildozer
@@ -38,7 +49,8 @@ jobs:
       - name: Build APK
         run: |
           export BUILDOZER_WARN_ON_ROOT=0
-          buildozer android clean
+          export P4A_NO_BINREPO_UPDATE=1
+
           buildozer -v android debug
 
       - name: Upload APK
